[package]
name = "eld-node"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Eld ABCI node application"
readme = "README.md"
authors.workspace = true
repository.workspace = true
homepage = "https://github.com/eldnetwork/eld-chain"
keywords = ["blockchain", "tendermint", "abci"]
publish = false

[[bin]]
name = "eld-node"
path = "src/main.rs"

[dependencies]
abci-rs = { workspace = true, features = ["use-tokio"] }
async-trait = "0.1.77"
axum = { version = "0.8.1", features = ["ws"] }
eld_common = { path = "../common", version = "0.0.1", package = "eld-common" }
eld_client = { path = "../client", version = "0.0.1", package = "eld-client" }
base64.workspace = true
bincode.workspace = true
bytes = "1.5.0"
clap = { version = "4.0", features = ["derive"] }
hex.workspace = true
libc = "0.2"
rocksdb = "0.21.0"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
blake3.workspace = true
tendermint-rpc.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt", "time"] }
url.workspace = true
chrono = "0.4.40"
futures-util = "0.3"
rand.workspace = true
ed25519-dalek = { workspace = true, features = ["pem", "pkcs8"] }
lz4 = "1.24.0"
tower = { version = "0.4", features = ["util", "limit"] }
tower-http = { version = "0.5", features = ["cors"] }
reqwest = { workspace = true, features = ["json"] }
patricia_tree = "0.10.1"
trie-db = "=0.31.0"
memory-db = "0.32"
hash-db = "0.16"
reference-trie = "=0.29.2"
hash256-std-hasher = "0.15.2"
libp2p = { version = "0.53.2", features = [
    "tcp",
    "noise",
    "yamux",
    "gossipsub",
    "mdns",
    "quic",
    "tokio",
    "macros",
] }

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
